name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Chạy trên máy ảo EC2 của bạn

    strategy:
      matrix:
        node-version: [20.x] # Dùng bản Node ổn định

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # Quan trọng: Chỉ định đường dẫn file lock để cache hoạt động đúng
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json

    # --- PHẦN BACKEND (NestJS) ---
    - name: Install Backend Dependencies
      working-directory: ./backend  # Đi vào thư mục backend
      run: npm ci --legacy-peer-deps

    - name: Build Backend
      working-directory: ./backend
      run: npm run build

    # --- PHẦN FRONTEND (Next.js) ---
    - name: Install Frontend Dependencies
      working-directory: ./frontend  # Đi vào thư mục frontend
      run: npm ci --legacy-peer-deps

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build